config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create 
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten
      flash[:notice] = "Kitten Created!"
    else
      flash.now[:alert] = "Creation unsuccessful!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten
      flash[:notice] = "Edit Successful!"
    else
      flash.now[:alert] = "Edit unsuccessful!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])

    if @kitten.destroy
      redirect_to root_path, status: :see_other
      flash[:notice] = "Delete Successful!"
    else
      flash.now[:alert] = "Deletion unsuccessful!"
      redirect_to @kitten
    end

  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness %>
  </div>

  <div class="field">
    <%= form.label :softness %><br>
    <%= form.number_field :softness %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to "Home", root_path %>

app/views/kittens/edit.html.erb
<p>Edit Kitten</p>

<%= render 'form' %>

app/views/kittens/index.html.erb
<% @kittens.each do |kitten| %>
  <p>Name: <%= kitten.name %></p>
  <%= link_to "Show Kitten", kitten %> | <%= link_to "Edit Kitten", edit_kitten_path(kitten) %> | <%= link_to "Delete Kitten", kitten, data: { turbo_method: :delete } %>
<% end %>
<br>
<br>
<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<p>New Kitten</p>

<%= render 'form' %>

app/views/kittens/show.html.erb
<p>Name: <%= @kitten.name %></p>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %> </p>
<br>
<%= link_to "Edit Kitten", edit_kitten_path %> | <%= link_to "Delete Kitten", @kitten, data: { turbo_method: :delete } %> | <%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>